(function(){
'use strict';
if(window.__worshipCoreAppInstalled)return;window.__worshipCoreAppInstalled=true;
window.base=window.base||{};window.transposeSource=window.transposeSource||{};window.arrangement=window.arrangement||[];window.activeSection=window.activeSection||'';window.currentSongTitle=window.currentSongTitle||'Imported Song';window.currentArtist=window.currentArtist||'Unknown Artist';window.currentKey=window.currentKey||'C';window.size=window.size||18;window.editMode=!!window.editMode;window.scrollTimer=window.scrollTimer||null;
function esc(s){return String(s==null?'':s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
window.esc=window.esc||esc;
window.toast=window.toast||function(m){const t=document.getElementById('toast');if(!t)return;t.textContent=m;t.style.display='block';clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>t.style.display='none',1700);};
window.showTab=function(t){['songs','setlists','song'].forEach(id=>{const e=document.getElementById(id);if(e)e.classList.toggle('hidden',id!==t);});const sn=document.getElementById('songsNav'),ln=document.getElementById('setlistsNav');if(sn)sn.classList.toggle('active',t==='songs');if(ln)ln.classList.toggle('active',t==='setlists');if(t==='song')window.renderSong();};
window.openSong=function(){window.showTab('song');};
function chordOnly(rows){return rows.length&&rows.every(r=>String(r&&r[0]||'').trim()&&!String(r&&r[1]||'').trim());}
function renderLine(pi,li,row){const chord=String(row&&row[0]||'').trim(),lyric=String(row&&row[1]||'');return '<div class="line"><div class="chordRow"><input class="chordInput" value="'+esc(chord)+'" '+(window.editMode?'':'readonly')+' onchange="updateLine('+pi+','+li+',0,this.value)" aria-label="Chord"></div>'+(lyric.trim()?'<div class="lyricText">'+esc(lyric)+'</div>':'')+'</div>';}
window.renderSong=function(){const arr=Array.isArray(window.arrangement)&&window.arrangement.length?window.arrangement:Object.keys(window.base||{});window.arrangement=arr;if(!window.activeSection||!arr.includes(window.activeSection))window.activeSection=arr[0]||'';const title=document.getElementById('songTitle'),artist=document.getElementById('songArtist'),key=document.getElementById('key'),lt=document.getElementById('libraryTitle'),la=document.getElementById('libraryArtist');if(title)title.textContent=window.currentSongTitle;if(artist)artist.textContent=window.currentArtist;if(key)key.textContent=window.currentKey;if(lt)lt.textContent=window.currentSongTitle;if(la)la.textContent=window.currentArtist+' • Key '+window.currentKey;const tabs=document.getElementById('tabs');if(tabs)tabs.innerHTML=arr.map((p,i)=>'<button type="button" class="btn '+(p===window.activeSection?'sectionActive':'')+'" onclick="jump('+i+')">'+esc(p)+'</button>').join('');const content=document.getElementById('content');if(content)content.innerHTML=arr.map((p,i)=>{const rows=Array.isArray(window.base[p])?window.base[p]:[];return '<section class="card '+(p===window.activeSection?'sectionActive ':'')+(chordOnly(rows)?'chordOnlySection':'')+'" id="part'+i+'"><div class="part-title">'+esc(p)+'</div>'+rows.map((r,j)=>renderLine(i,j,r)).join('')+(window.editMode?'<div class="controls"><button type="button" class="btn" onclick="addLine('+i+')">＋ Add lyric line</button><button type="button" class="btn" onclick="addChordLine('+i+')">＋ Add chord line</button></div>':'')+'</section>';}).join('');const song=document.getElementById('song');if(song)song.classList.toggle('editMode',window.editMode);const eb=document.getElementById('editBtn');if(eb)eb.textContent=window.editMode?'✓ Done Editing':'✎ Edit';const sb=document.getElementById('saveBtn');if(sb)sb.style.display=window.editMode?'inline-block':'none';window.applyFont();};
window.jump=function(i){const arr=window.arrangement||[];if(!arr[i])return;window.activeSection=arr[i];window.renderSong();const el=document.getElementById('part'+i);if(el)el.scrollIntoView({behavior:'smooth',block:'start'});};
window.applyFont=function(){document.querySelectorAll('#content .lyricText').forEach(e=>e.style.fontSize=(window.size||18)+'px');document.querySelectorAll('#content .chordInput').forEach(e=>e.style.fontSize=Math.max(12,(window.size||18)-2)+'px');};
window.font=function(n){window.size=Math.max(14,Math.min(30,(window.size||18)+n));window.applyFont();};
window.toggleEdit=function(){window.editMode=!window.editMode;window.renderSong();window.toast(window.editMode?'Edit mode on':'Edit mode closed');};
window.updateLine=function(pi,li,field,val){const p=window.arrangement[pi];if(window.base[p]&&window.base[p][li]){window.base[p][li][field]=val;window.transposeSource=JSON.parse(JSON.stringify(window.base));if(typeof window.saveLocal==='function')window.saveLocal(false);window.renderSong();}};
window.addLine=function(pi){const p=window.arrangement[pi];(window.base[p]||(window.base[p]=[])).push(['','']);window.renderSong();};
window.addChordLine=function(pi){const p=window.arrangement[pi];(window.base[p]||(window.base[p]=[])).push(['C','']);window.renderSong();};
window.autoScroll=function(){if(window.scrollTimer){clearInterval(window.scrollTimer);window.scrollTimer=null;window.toast('Auto-scroll stopped');return;}window.scrollTimer=setInterval(()=>window.scrollBy(0,1),45);window.toast('Auto-scroll started');};
window.saveLocal=window.saveLocal||function(show){try{localStorage.setItem('worshipChordsApp',JSON.stringify({base:window.base,transposeSource:window.transposeSource,arrangement:window.arrangement,size:window.size,currentSongTitle:window.currentSongTitle,currentArtist:window.currentArtist,currentKey:window.currentKey,activeSection:window.activeSection}));if(show!==false)window.toast('Saved locally');}catch(e){}};
window.transpose=window.transpose||function(){const modal=document.getElementById('modal'),body=document.getElementById('modalBody');if(!modal||!body)return;const keys=['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];body.innerHTML='<div class="row"><h2>Transpose</h2><button class="btn" onclick="closeModal()">Close</button></div><div class="keygrid">'+keys.map(k=>'<button class="keybtn '+(k===window.currentKey?'selected':'')+'" onclick="applyTransposeKey(\''+k+'\')">'+k+'</button>').join('')+'</div>';modal.style.display='flex';};
window.applyTransposeKey=function(target){const keys=['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];const from=keys.indexOf(window.currentKey),to=keys.indexOf(target);if(from<0||to<0)return;const interval=(to-from+12)%12;Object.keys(window.base||{}).forEach(p=>{window.base[p]=(window.base[p]||[]).map(r=>[window.transposeChord?window.transposeChord(r[0],interval):r[0],r[1]]);});window.currentKey=target;window.transposeSource=JSON.parse(JSON.stringify(window.base));window.closeModal();window.renderSong();if(typeof window.saveLocal==='function')window.saveLocal(false);window.toast('Song is now in the key of '+target);};
window.closeModal=function(){const m=document.getElementById('modal');if(m)m.style.display='none';};
window.loadLocal=function(){try{const d=JSON.parse(localStorage.getItem('worshipChordsApp')||'null');if(!d)return;if(d.base)window.base=d.base;if(d.transposeSource)window.transposeSource=d.transposeSource;else window.transposeSource=JSON.parse(JSON.stringify(window.base));if(Array.isArray(d.arrangement))window.arrangement=d.arrangement;if(d.size)window.size=d.size;if(d.currentSongTitle)window.currentSongTitle=d.currentSongTitle;if(d.currentArtist)window.currentArtist=d.currentArtist;if(d.currentKey)window.currentKey=d.currentKey;if(d.activeSection)window.activeSection=d.activeSection;}catch(e){}};
window.loadLocal();window.renderSong();
})();