(function(){'use strict';
if(window.__phase1UiInstalled)return;window.__phase1UiInstalled=true;
function install(){
 const app=document.querySelector('.app'); if(!app)return;
 const songs=document.getElementById('songs'), setlists=document.getElementById('setlists'), song=document.getElementById('song'); if(!songs||!setlists||!song)return;
 const icon={home:'<svg viewBox="0 0 24 24"><path d="M3 10.8 12 3l9 7.8v9.2a1 1 0 0 1-1 1h-5.5v-6h-5v6H4a1 1 0 0 1-1-1z"/></svg>',library:'<svg viewBox="0 0 24 24"><path d="M4 4.5A2.5 2.5 0 0 1 6.5 2H20v17H6.5A2.5 2.5 0 0 0 4 21.5zM4 4.5v17M8 6h8M8 10h8"/></svg>',lyrics:'<svg viewBox="0 0 24 24"><path d="M9 18V5l10-2v13"/><circle cx="6.5" cy="18" r="3"/><circle cx="16.5" cy="16" r="3"/></svg>',menu:'<svg viewBox="0 0 24 24"><path d="M5 6h14M5 12h14M5 18h14"/></svg>',search:'<svg viewBox="0 0 24 24"><circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 5 5"/></svg>'};
 const home=document.createElement('main'); home.id='phase1Home'; home.className='hidden'; home.innerHTML='<div class="p1home"><div class="p1brand">The Disciples</div><div class="p1sub">Soli Deo Gloria</div><button id="p1Search" class="p1search" type="button" aria-label="Search or import song">'+icon.search+'</button><div class="p1hint">Search or import song</div></div>';
 const menu=document.createElement('main'); menu.id='phase1Menu'; menu.className='hidden'; menu.innerHTML='<div class="p1menu"><h1>Menu</h1><div class="card"><b>Settings</b><div class="muted" style="margin-top:5px">More settings will be added here.</div></div></div>';
 app.insertBefore(home,songs); app.appendChild(menu);
 const bottom=document.createElement('nav'); bottom.id='phase1Bottom'; bottom.innerHTML='<button data-p="home" aria-label="Home">'+icon.home+'</button><button data-p="library" aria-label="Library">'+icon.library+'</button><button data-p="lyrics" aria-label="Lyrics">'+icon.lyrics+'</button><button data-p="menu" aria-label="Menu">'+icon.menu+'</button>'; app.appendChild(bottom);
 const style=document.createElement('style'); style.textContent='#phase1Bottom{position:fixed;left:50%;bottom:0;transform:translateX(-50%);width:min(920px,100%);height:62px;background:#151a20;border-top:1px solid #293039;display:flex;z-index:9999;padding-bottom:env(safe-area-inset-bottom)}#phase1Bottom button{flex:1;border:0;background:none;color:#8f99a4;display:flex;align-items:center;justify-content:center}#phase1Bottom button.active{color:#fff}#phase1Bottom svg{width:24px;height:24px;fill:none;stroke:currentColor;stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}body{padding-bottom:62px}.p1home{min-height:calc(100vh - 140px);display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}.p1brand{font-size:30px;font-weight:800}.p1sub{color:#929ca6;margin-top:5px}.p1search{margin-top:42px;width:72px;height:72px;border:1px solid #39424c;border-radius:50%;background:#171c22;color:#fff;display:flex;align-items:center;justify-content:center}.p1search svg{width:32px;height:32px;fill:none;stroke:currentColor;stroke-width:1.6;stroke-linecap:round;stroke-linejoin:round}.p1hint{font-size:12px;color:#929ca6;margin-top:12px}.p1menu{padding:18px}'; app.appendChild(style);
 document.querySelector('body> .app>header')?.querySelector('button')?.style.setProperty('display','none'); const oldNav=app.querySelector(':scope > nav:not(#phase1Bottom)'); if(oldNav)oldNav.style.display='none';
 function page(p){home.classList.toggle('hidden',p!=='home'); songs.classList.toggle('hidden',p!=='library'); setlists.classList.add('hidden'); song.classList.toggle('hidden',p!=='lyrics'); menu.classList.toggle('hidden',p!=='menu'); bottom.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.p===p)); if(p==='library'){songs.classList.remove('hidden');setlists.classList.add('hidden');} if(p==='lyrics'&&typeof window.renderSong==='function')window.renderSong();}
 bottom.querySelectorAll('button').forEach(b=>b.onclick=function(){page(b.dataset.p)});
 document.getElementById('p1Search').onclick=function(){if(typeof window.openSearch==='function')window.openSearch()};
 page('home');
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();